name: 'Vue to Github Pages reloaded'
branding:
  icon: 'activity'  
  color: 'blue'
description: 'This Action will Build your Vue Project and deploy it to Github Pages'
inputs:
  username:
    description: 'Your username'
    required: true
  reponame:
    description: 'Your reponame'
    required: true
  token:
    description: 'Your Github token'
    required: true
  gitemail:
    description: 'Your git commit email'
    required: false
    default: 'CI@example.com'
  gitname:
    description: 'Your git commit name'
    required: false
    default: 'CI'
  gitmsg:
    description: 'Your git commit message'
    required: false
    default: 'deploy'
  cname:
    description: 'Your custom domain'
    required: false
    default: 'none'
  useyarn:
    description: 'Use yarn to build'
    required: false
    default: false
runs:
  using: "composite"
  steps:
      - name: Build Vue
        run: |
              git config --global user.email "${{ inputs.gitemail }}"
              git config --global user.name "${{ inputs.gitname }}"
              mkdir dist 
              cd dist
              
              git init
              
              git remote add origin https://${{ inputs.username }}:${{ inputs.token }}@github.com/${{ inputs.username }}/${{ inputs.reponame }}.git -m pages
              git fetch
              echo fetch
              git branch -m pages
              echo branch
              echo temp >log.txt
              git add *
              git commit -m temp
              
              git branch --set-upstream-to=origin 
              echo branch 2
              git remote -v
              echo test
              git fetch
              echo fetch
              git pull --rebase
              echo pull
             
              cd ..
              
              if [ true ==  ${{ inputs.useyarn }} ]; then yarn install --frozen-lockfile; else npm i; fi
              if [ true ==  ${{ inputs.useyarn }} ]; then yarn build; else npm run build; fi
           
              git pull 
              git push
              cd dist
              ln -s index.html 404.html
              if [ "none" !=  ${{ inputs.cname }} ]; then echo '${{ inputs.cname }}' > CNAME; fi
              
              git add -A
              git commit -m '${{ inputs.gitmsg }}'
              if ! git diff --quiet remotes/origin/HEAD; then   git push ; fi
              cd ..
              git add -A
              git commit -m "update"
              git push
        shell: bash
