name: Releases

on: 
  push:
    branches: ["main"]
    

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: alphaleadership/release-action@1.0.0
      with:
        tag: "la"
        generateReleaseNotes: true
        skipIfReleaseExists: false
        makeLatest: true
        artifacts: "release.tar.gz,foo/*.txt"
        bodyFile: "README.md"
