name: Releases

on: 
  push:
    branches: ["main"]
    

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        tag: "latest"
        generateReleaseNotes: true
        skipIfReleaseExists: false
        artifacts: "release.tar.gz,foo/*.txt"
        bodyFile: "readme.md"
